// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace RITNow
{
	public partial class SelectStopTableViewController : UITableViewController
	{
		public SelectStopTableViewController (IntPtr handle) : base (handle)
		{

		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.TableView.Source=new StopListTableViewSource(this.TableView);
		}
	}
}
