// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace RITNow
{
	public partial class TestTableViewController : UITableViewController
	{
		public TestTableViewController (IntPtr handle) : base (handle)
		{

		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad();
			TableView.Source=new TestTableSource();
		}
	}
	class TestTableSource : UITableViewSource{
		public override int RowsInSection (UITableView tableview, int section)
		{
			return 5;
		}
		public override int NumberOfSections (UITableView tableView)
		{
			return 1;
		}
		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell= tableView.DequeueReusableCell("proto1");
			Console.WriteLine ("cell={0}", cell);
			return cell;
		}
	}
}
