// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace RITNow
{
	public partial class SelectStopViewController : UIViewController
	{
		public SelectStopViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.TableView.Source = new StopListTableViewSource (this);
		}
		public void Close ()
		{
			DismissModalViewControllerAnimated(true);
		}
		partial void closeButtonTouched (NSObject sender)
		{
			Close();
		}
		public void Reload ()
		{
			TableView.ReloadData();
		}

	}
}
